Adding more error handling, removing unused variables, and fixing double frees.
Summary:
Improved error handling, unused variables, and double frees.

Build: FreeBSD 12.1-RELEASE PERF
Host: skylake4.rcs.uwaterloo.ca
Test started: Sat Aug 21 15:38:30 UTC 2021
Stress testing: OFF
Test                                       Status      Time
-----------------------------------------------------------
001-load-unload.sh                       [ success ]      3
002-load-mount-unload.sh                 [ success ]      3
003-mount-unmount.sh                     [ success ]      1
004-load-double-sls.sh                   [ success ]      1
005-unload-double-sls.sh                 [ success ]      1
006-load-double-slos.sh                  [ success ]      1
007-unload-double-slos.sh                [ success ]      1
008-mount-double.sh                      [ success ]      1
009-unload-slos-before-sls.sh            [ success ]      1
010-unmount-before-sls.sh                [ success ]      0
101-simple-file-io.sh                    [ success ]      2
102-fd-chroot.sh                         [ success ]      5
201-simple-mem-ckpt.sh                   [ success ]      2
202-simple-osd-ckpt.sh                   [ success ]      2
203-busy-loop.sh                         [ success ]      3
204-print-stdout.sh                      [ success ]      5
205-array-traversal.sh                   [ success ]      4
206-mmap-file.sh                         [ success ]      5
207-mmap-anonymous.sh                    [ success ]      3
208-signal-handler.sh                    [ success ]      5
209-pthreads-mutex.sh                    [ success ]      5
210-file-vnode.sh                        [ success ]      6
211-fork-simple.sh                       [ success ]      6
212-file-fifo.sh                         [ success ]      5
214-file-pipes.sh                        [ success ]      5
215-file-posixshm.sh                     [ success ]      4
216-sysv-shm.sh                          [ success ]      4
217-file-udplisten.sh                    [ success ]      6
218-file-tcplisten.sh                    [ success ]     14
219-kqueue.sh                            [ success ]      6
220-pgroups.sh                           [ success ]     23
221-lazy-osd-ckpt.sh                     [ success ]      3
222-self-ckpt-mem.sh                     [ success ]      7
223-restore-mem-multiple.sh              [ success ]      3
224-restore-osd-multiple.sh              [ success ]      4
225-memsnap-osd-poll.sh                  [ success ]      5
226-memsnap-osd-block.sh                 [ success ]      6
227-memsnap-mem.sh                       [ success ]      2
228-wal.sh                               [ success ]      1
229-chroot.sh                            [ disabled ]    N/A
230-chroot-devfs.sh                      [ disabled ]    N/A
231-memsnap-osd-nowait.sh                [ success ]      6
232-metropolis.sh                        [ success ]      1
233-metropolis-fork.sh                   [ success ]      1
234-metropolis-exec.sh                   [ success ]      1
235-metropolis-accept.sh                 [ success ]      1
236-metropolis-exit.sh                   [ success ]      4
237-metropolis-accept4.sh                [ success ]      1
238-metropolis-pymetro.sh                [ disabled ]    N/A
239-metropolis-pymetro-multiple.sh       [ disabled ]    N/A
240-metropolis-pymetro-partitions.sh     [ disabled ]    N/A
241-metropolis-pymetro-cachedparts.sh    [ disabled ]    N/A
242-cached-restore.sh                    [ success ]      8
243-prefault-restore.sh                  [ success ]      9
244-precopy-restore.sh                   [ success ]      9
301-mem-rest.sh                          [ success ]      6

Test Plan: testbench

Reviewers: tavianator, etsal, ryan

Reviewed By: etsal, ryan

Differential Revision: https://review.rcs.uwaterloo.ca/D588

diff --git a/tests/aurora b/tests/aurora
--- a/tests/aurora
+++ b/tests/aurora
@@ -179,8 +179,12 @@ createroot()
 {
     if [ ! -f "$SLSROOT" ]; then
 	$SRCROOT/scripts/image.sh
-	$SRCROOT/scripts/rootmin.sh
     fi
+    if [ ! -f "$SLSROOT" ]; then
+	echo "Failed to create root image for testing!"
+	exit 1
+    fi
+    $SRCROOT/scripts/rootmin.sh
 }
 
 installroot()
